# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UIoT-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyJSON'
  pod 'Alamofire'

  # Pods for UIoT-iOS

  target 'UIoT-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UIoT-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
